Repository Team-return/JOBIS-FE, pull requests merged in 2024-10, with the labels that each got.

#109 이메일 형식 오류 핸들링 (#108)
  apps/company/src/app/registration/page.tsx
Labels: chore

#110 기업 수정 시 사업 분야, 사업 등록증 비활성화 처리
  apps/company/src/apis/company/types.ts
  apps/company/src/app/registration/page.tsx
Labels: chore

#117 컴퍼니 코드 오류 수정
  apps/company/src/app/registration/page.tsx
Labels: 버그, chore

#119 담당자 2, 팩스 번호 삭제
  apps/company/src/apis/company/types.ts
  apps/company/src/app/registration/page.tsx
  apps/company/src/components/inputTemplate/index.tsx
Labels: chore

#123 본사 체크박스 구현
  apps/company/public/checkImg.svg
  apps/company/src/apis/company/types.ts
  apps/company/src/app/registration/page.tsx
Labels: chore, 기능추가

#126 회사 소개 글자수 제한
  apps/company/src/app/registration/page.tsx
Labels: chore

#137 채널톡 추가
  .pnp.cjs
  .yarn/cache/@channel.io-channel-web-sdk-loader-npm-2.0.0-a716027852-11bf96fa88.zip
  apps/company/package.json
  apps/company/src/app/layout.tsx
  yarn.lock
Labels: 기능추가
